runtime: php72


handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /assets/styles
  static_dir: assets/styles
  
- url: /assets/scripts
  static_dir: assets/styles

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: .*
  script: auto